"use client";
import { CSSProperties, ReactNode, useCallback, useEffect, useMemo, useState } from "react";
import { CombinationStat, CoopGroup, combinationStats, featuredCombinations } from "@/domain/coopLadder";
import { characterById, characters } from "@/domain/ladder";
import { CharacterId } from "@/domain/types";
import { CoopRepository } from "@/storage/coopRepository";

const fmt = new Intl.DateTimeFormat("ru-RU", { day: "2-digit", month: "short", year: "numeric" });
const getCharacter = (id: CharacterId) => characterById(id);

export default function CoopChallenge({ repository, userId, onBack }: { repository: CoopRepository | null; userId: string; onBack: () => void }) {
  const [groups, setGroups] = useState<CoopGroup[]>([]), [profiles, setProfiles] = useState<{id:string;username:string}[]>([]), [openId, setOpenId] = useState<string | null>(null);
  const [creating, setCreating] = useState(false), [name, setName] = useState(""), [invited, setInvited] = useState<string[]>([]), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const [deleting, setDeleting] = useState<CoopGroup | null>(null);
  const load = useCallback(async () => { if (!repository) return; try { const [nextGroups, nextProfiles] = await Promise.all([repository.groups(), repository.profiles()]); setGroups(nextGroups); setProfiles(nextProfiles); setError(""); } catch (caught) { setError(caught instanceof Error ? caught.message : "Не удалось загрузить группы."); } }, [repository]);
  useEffect(() => { void load(); }, [load]);
  const act = async (action: () => Promise<void>) => { setBusy(true); setError(""); try { await action(); await load(); } catch (caught) { const message = caught instanceof Error ? caught.message : "Не удалось выполнить действие."; setError(message.includes("STALE_") ? "Данные уже изменил другой участник. Обновите страницу и повторите действие." : message); } finally { setBusy(false); } };
  if (!repository) return <main className="ladder"><button className="back" onClick={onBack}>← Все челленджи</button><section className="panel coopUnavailable"><p className="eyebrow">CO-OP</p><h1>Нужен аккаунт</h1><p className="muted">Группы и приглашения доступны после входа в аккаунт. Demo-режим не может синхронизировать данные между игроками.</p></section></main>;
  const pending = groups.filter((group) => group.members.find((member) => member.userId === userId)?.status === "pending");
  const active = groups.filter((group) => group.members.every((member) => member.status === "accepted"));
  const waiting = groups.filter((group) => !pending.includes(group) && !active.includes(group));
  const open = active.find((group) => group.id === openId);
  if (open) return <GroupDetails group={open} repository={repository} busy={busy} error={error} reload={load} act={act} onBack={() => setOpenId(null)} />;
  return <main className="ladder">
    <button className="back" onClick={onBack}>← Все челленджи</button>
    <div className="ladderHead"><div><p className="eyebrow">КОМАНДНОЕ ИСПЫТАНИЕ</p><h1>Co-op Ladder Challenge</h1><p>Соберите группу из 2–4 игроков и пройдите A1–A10 вместе. Любое поражение завершает общую попытку.</p></div><button className="primary" onClick={() => setCreating(true)}>+ Создать группу</button></div>
    {error && <div className="errorBanner inlineError">{error} <button onClick={() => void load()}>Обновить</button></div>}
    {pending.length > 0 && <section className="panel"><div className="panelHead"><div><p className="eyebrow">ПРИГЛАШЕНИЯ</p><h2>Вас зовут в группу</h2></div></div>{pending.map((group) => <div className="groupRow" key={group.id}><div><b>{group.name}</b><small>{group.members.map((m) => `@${m.username}`).join(" · ")}</small></div><div><button className="ghost" disabled={busy} onClick={() => void act(() => repository.answer(group.id, false))}>Отклонить</button><button className="primary" disabled={busy} onClick={() => void act(() => repository.answer(group.id, true))}>Принять</button></div></div>)}</section>}
    <section className="panel"><div className="panelHead"><div><p className="eyebrow">ВАШИ ГРУППЫ</p><h2>Активные группы</h2></div></div>{active.length ? active.map((group) => <button className="groupCard" key={group.id} onClick={() => setOpenId(group.id)}><div><h3>{group.name}</h3><p>{group.members.map((m) => `@${m.username}`).join(" · ")}</p></div><span>{group.activeRun ? `A${group.activeRun.currentAscension} · в процессе` : "Открыть →"}</span><button className="iconDanger" aria-label="Удалить группу" onClick={(event) => { event.stopPropagation(); setDeleting(group); }}>×</button></button>) : <div className="empty">Активных групп пока нет.<br/><small>Создайте группу или примите приглашение.</small></div>}</section>
    {waiting.length > 0 && <section className="panel"><div className="panelHead"><div><p className="eyebrow">ОЖИДАНИЕ</p><h2>Ждём участников</h2></div></div>{waiting.map((group) => <div className="groupRow" key={group.id}><div><b>{group.name}</b><small>{group.members.map((m) => `@${m.username} — ${m.status === "accepted" ? "принял" : "ожидает"}`).join(" · ")}</small></div><button className="iconDanger" onClick={() => setDeleting(group)}>×</button></div>)}</section>}
    {creating && <div className="modalShade" onClick={() => setCreating(false)}><div className="modal createGroupModal" onClick={(e) => e.stopPropagation()}><p className="eyebrow">НОВАЯ ГРУППА</p><h2>Соберите команду</h2><label>Название группы<input autoFocus maxLength={60} value={name} onChange={(e) => setName(e.target.value)} placeholder="Например, Башня друзей" /></label><p className="fieldLabel">Участники · выберите от 1 до 3</p><div className="profilePicker">{profiles.map((profile) => <label key={profile.id}><input type="checkbox" checked={invited.includes(profile.id)} disabled={!invited.includes(profile.id) && invited.length === 3} onChange={() => setInvited((current) => current.includes(profile.id) ? current.filter((id) => id !== profile.id) : [...current, profile.id])}/><span>@{profile.username}</span></label>)}</div><div><button className="ghost" onClick={() => setCreating(false)}>Отмена</button><button className="primary" disabled={busy || !name.trim() || invited.length < 1} onClick={() => void act(async () => { await repository.create(name, invited); setCreating(false); setName(""); setInvited([]); })}>Создать и пригласить</button></div></div></div>}
    {deleting && <Confirm title="Удалить группу?" text={`Группа «${deleting.name}» и вся её история будут удалены без возможности восстановления.`} onCancel={() => setDeleting(null)} onConfirm={() => void act(async () => { await repository.remove(deleting.id); setDeleting(null); })} />}
  </main>;
}

function GroupDetails({ group, repository, busy, error, reload, act, onBack }: { group: CoopGroup; repository: CoopRepository; busy:boolean; error:string; reload:()=>Promise<void>; act:(fn:()=>Promise<void>)=>Promise<void>; onBack:()=>void }) {
  const ids = useMemo(() => group.members.map((member) => member.userId), [group.members]);
  const stats = useMemo(() => combinationStats(ids, group.history), [ids, group.history]);
  const featured = useMemo(() => featuredCombinations(stats), [stats]);
  const [assignments, setAssignments] = useState<Record<string, CharacterId>>({}), [confirming, setConfirming] = useState<Record<string, CharacterId> | null>(null), [allOpen, setAllOpen] = useState(false), [allPage, setAllPage] = useState(1), [historyPage, setHistoryPage] = useState(1);
  const availableCharacters = useMemo(() => characters.filter((character) => character.available).sort((a, b) => a.order - b.order), []);
  const allAssigned = ids.every((id) => assignments[id]);
  const choose = (value: Record<string, CharacterId>) => setAssignments(value);
  const chooseRandomly = () => setAssignments(Object.fromEntries(ids.map((id) => [id, availableCharacters[Math.floor(Math.random() * availableCharacters.length)].id])));
  return <main className="ladder coopDetail"><button className="back" onClick={onBack}>← Мои группы</button><div className="ladderHead"><div><p className="eyebrow">CO-OP LADDER · {group.members.length} ИГРОКА</p><h1>{group.name}</h1><p>{group.members.map((m) => `@${m.username}`).join(" · ")}</p></div></div>{error && <div className="errorBanner inlineError">{error} <button onClick={() => void reload()}>Обновить страницу</button></div>}
    {group.activeRun ? <ActiveRun group={group} busy={busy} act={act} repository={repository} /> : <section className="panel characterSelection"><div className="panelHead"><div><p className="eyebrow">НОВЫЙ ЗАБЕГ</p><h2>Выберите персонажей</h2></div></div><div className="playerChoices">{group.members.map((member) => { const selected = assignments[member.userId]; const selectedCharacter = selected ? getCharacter(selected) : null; return <article className="playerChoiceCard" key={member.userId}><header className="playerIdentity"><span className="playerAvatar" aria-hidden="true">{member.username.slice(0, 2).toUpperCase()}</span><div><h3>@{member.username}</h3><p>{selectedCharacter ? <>Выбран: <strong>{selectedCharacter.name}</strong></> : "Персонаж не выбран"}</p></div></header><div className="characterPicker" aria-label={`Выбор персонажа для ${member.username}`}>{availableCharacters.map((character) => { const isSelected = selected === character.id; return <button type="button" key={character.id} className={isSelected ? "characterOption selected" : "characterOption"} style={{ "--character-color": character.color } as CSSProperties} aria-pressed={isSelected} onClick={() => setAssignments((current) => ({ ...current, [member.userId]: character.id }))}><span className="characterIcon" aria-hidden="true">{character.initials}</span><span className="characterName">{character.name}</span><span className="selectionState">{isSelected ? "✓ Выбран" : "Выбрать"}</span></button>})}</div></article>})}</div><div className="selectionFooter"><div className="selectionSummary"><div className="summaryHead"><div><p className="eyebrow">ИТОГОВЫЙ СОСТАВ</p><h3>Команда</h3></div><button type="button" className="random" onClick={chooseRandomly}>↻ Выбрать случайно</button></div><ul>{group.members.map((member) => <li key={member.userId}><span>@{member.username}</span><strong>{assignments[member.userId] ? getCharacter(assignments[member.userId]).name : "Не выбран"}</strong></li>)}</ul></div><div className="startArea"><button className="primary start" disabled={busy || !allAssigned} onClick={() => setConfirming(assignments)}>Начать забег</button>{!allAssigned && <small>Выберите персонажа для каждого участника</small>}</div></div></section>}
    <section className="panel"><div className="panelHead"><div><p className="eyebrow">СВЯЗКИ</p><h2>Статистика команды</h2></div><button className="ghost" onClick={() => setAllOpen(true)}>Все {stats.length} связок</button></div><div className={`featuredGrid${group.activeRun ? " active" : ""}`}><CombinationList title="Топ-3" items={featured.best} group={group} onChoose={group.activeRun ? undefined : choose}/><CombinationList title="Худшие" items={featured.worst} group={group} onChoose={group.activeRun ? undefined : choose}/>{!group.activeRun && <CombinationList title={featured.random.some((x) => x.runs === 0) ? "Ещё не играли" : "Случайные"} items={featured.random} group={group} onChoose={choose}/>}</div></section>
    {group.members.length === 2 && <Matrix group={group} stats={stats} onChoose={choose}/>}
    <History group={group} page={historyPage} setPage={setHistoryPage}/>
    {confirming && <Confirm title="Начать забег этим составом?" text={assignmentLines(group, confirming)} cancelLabel="Вернуться к выбору" confirmLabel="Начать забег" onCancel={() => setConfirming(null)} onConfirm={() => void act(async () => { await repository.start(group.id, confirming, group.updatedAt); setConfirming(null); })}/>}
    {allOpen && <div className="modalShade" onClick={() => setAllOpen(false)}><div className="modal allStatsModal" onClick={(e) => e.stopPropagation()}><div className="panelHead"><div><p className="eyebrow">ВСЕ СВЯЗКИ</p><h2>{stats.length} вариантов</h2></div><button className="ghost" onClick={() => setAllOpen(false)}>Закрыть</button></div><CombinationList title="По результативности" items={stats.slice((allPage-1)*20, allPage*20)} group={group} onChoose={(a) => { setAllOpen(false); choose(a); }}/><Pager page={allPage} pages={Math.ceil(stats.length/20)} setPage={setAllPage}/></div></div>}
  </main>;
}

function ActiveRun({ group, repository, busy, act }: { group:CoopGroup; repository:CoopRepository; busy:boolean; act:(fn:()=>Promise<void>)=>Promise<void> }) { const run=group.activeRun!; const finish=(result:"win"|"lose")=>void act(()=>repository.finish(group.id,run.id,result,group.updatedAt)); return <section className="activeRun"><div className="runTop"><div><p className="eyebrow">АКТИВНЫЙ ЗАБЕГ</p><h2>Состав команды</h2><p className="muted">Следующее испытание — Вознесение {run.currentAscension}{run.lastAttemptAt ? ` · последняя попытка ${fmt.format(new Date(run.lastAttemptAt))}` : ""}</p></div><strong>{run.completedAscensions}/10</strong></div><ActiveRoster group={group} assignments={run.assignments}/><div className="steps">{Array.from({length:10},(_,i)=><div key={i} className={i<run.completedAscensions?"done":i===run.completedAscensions?"current":""}><span>{i<run.completedAscensions?"✓":i+1}</span><small>A{i+1}</small></div>)}</div><div className="runActions"><button className="danger" disabled={busy} onClick={()=>finish("lose")}>Поражение</button><button className="primary" disabled={busy} onClick={()=>finish("win")}>{run.currentAscension===10?"Завершить челлендж":"Победа · перейти дальше"}</button></div></section> }
function ActiveRoster({group,assignments}:{group:CoopGroup;assignments:Record<string,CharacterId>}) { return <div className="activeRoster">{group.members.map((member)=>{const character=getCharacter(assignments[member.userId]);return <article className="activePlayerCard" key={member.userId} style={{"--character-color":character.color} as CSSProperties}><span className="activeCharacterIcon" aria-hidden="true">{character.initials}</span><div><small>ИГРОК</small><h3>@{member.username}</h3><p>{character.name}</p></div></article>})}</div> }
function CombinationList({title,items,group,onChoose}:{title:string;items:CombinationStat[];group:CoopGroup;onChoose?:(a:Record<string,CharacterId>)=>void}) { return <div className="combinationList"><h3>{title}</h3>{items.length?items.map((item)=>{const content=<><span>{assignmentLabel(group,item.assignments)}</span><small>{item.runs} заб. · A{item.average.toFixed(1)} · {item.wins} прох.</small>{onChoose && <b>Выбрать →</b>}</>;return onChoose?<button key={item.key} onClick={()=>onChoose(item.assignments)}>{content}</button>:<div className="combinationItem" key={item.key}>{content}</div>}):<p className="muted">Пока нет данных</p>}</div> }
function Matrix({group,stats,onChoose}:{group:CoopGroup;stats:CombinationStat[];onChoose:(a:Record<string,CharacterId>)=>void}) { const [a,b]=group.members; const max=Math.max(...stats.map(s=>s.wins*11+s.average),1); return <section className="panel matrixPanel"><div className="panelHead"><div><p className="eyebrow">МАТРИЦА</p><h2>{a.username} × {b.username}</h2></div></div><div className="matrix"><div/>{characters.map(c=><b key={c.id}>{c.name}</b>)}{characters.flatMap(ca=>[<b key={`h-${ca.id}`}>{ca.name}</b>,...characters.map(cb=>{const stat=stats.find(s=>s.assignments[a.userId]===ca.id&&s.assignments[b.userId]===cb.id)!;const score=(stat.wins*11+stat.average)/max;return <button key={`${ca.id}-${cb.id}`} style={{background:`color-mix(in srgb, #477c55 ${Math.round(score*75)}%, #2b1717)`}} onClick={()=>onChoose(stat.assignments)}><strong>{stat.runs}</strong><small>A{stat.average.toFixed(1)} · {stat.wins}✓</small></button>})])}</div></section> }
function History({group,page,setPage}:{group:CoopGroup;page:number;setPage:(n:number)=>void}) { const pages=Math.max(1,Math.ceil(group.history.length/5)); return <section className="panel history coopHistory"><div className="panelHead"><div><p className="eyebrow">АРХИВ</p><h2>История забегов</h2></div></div>{group.history.length?group.history.slice((page-1)*5,page*5).map(run=><div className={`historyRow ${run.status==="completed"?"success":""}`} key={run.id}><div><b>{assignmentLabel(group,run.assignments)}</b><small>Начат {fmt.format(new Date(run.startedAt))}{run.lastAttemptAt ? ` · последняя попытка ${fmt.format(new Date(run.lastAttemptAt))}` : ""}</small></div><span>{run.status==="completed"?"✦ Челлендж пройден":`Проиграли на A${run.currentAscension}`}</span></div>):<div className="empty">Завершённых забегов пока нет.</div>}<Pager page={page} pages={pages} setPage={setPage}/></section> }
function Pager({page,pages,setPage}:{page:number;pages:number;setPage:(n:number)=>void}) { return <div className="pager"><button disabled={page===1} onClick={()=>setPage(page-1)}>←</button><span>{page} / {pages}</span><button disabled={page===pages} onClick={()=>setPage(page+1)}>→</button></div> }
function Confirm({title,text,onCancel,onConfirm,cancelLabel="Отмена",confirmLabel="Подтвердить"}:{title:string;text:ReactNode;onCancel:()=>void;onConfirm:()=>void;cancelLabel?:string;confirmLabel?:string}) { return <div className="modalShade" onClick={onCancel}><div className="modal" role="dialog" aria-modal="true" aria-labelledby="confirm-title" onClick={(e)=>e.stopPropagation()}><span className="modalIcon" aria-hidden="true">!</span><h2 id="confirm-title">{title}</h2><div className="confirmContent">{text}</div><div><button className="ghost" onClick={onCancel}>{cancelLabel}</button><button className="primary" onClick={onConfirm}>{confirmLabel}</button></div></div></div> }
function assignmentLabel(group:CoopGroup, assignments:Record<string,CharacterId>) { return group.members.map((member)=>`${member.username}: ${getCharacter(assignments[member.userId]).name}`).join(" · "); }
function assignmentLines(group:CoopGroup, assignments:Record<string,CharacterId>) { return <ul className="confirmAssignments">{group.members.map((member) => <li key={member.userId}><span>@{member.username}</span><strong>{getCharacter(assignments[member.userId]).name}</strong></li>)}</ul>; }
