"use client";
import { CSSProperties, useCallback, useEffect, useMemo, useState } from "react";
import { CoopMasterGroup, coopMasterStats } from "@/domain/coopMasterRotation";
import { characters } from "@/domain/ladder";
import { CharacterId, MasterRotationMode } from "@/domain/types";
import { CoopMasterRepository } from "@/storage/coopMasterRepository";

const getCharacter=(id:CharacterId)=>characters.find(item=>item.id===id)!;
const fmt=new Intl.DateTimeFormat("ru-RU",{day:"2-digit",month:"short",year:"numeric"});

export default function CoopMasterRotationChallenge({repository,userId,onBack}:{repository:CoopMasterRepository|null;userId:string;onBack:()=>void}){
  const [groups,setGroups]=useState<CoopMasterGroup[]>([]),[profiles,setProfiles]=useState<{id:string;username:string}[]>([]),[openId,setOpenId]=useState<string|null>(null),[creating,setCreating]=useState(false),[name,setName]=useState(""),[invited,setInvited]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const load=useCallback(async()=>{if(!repository)return;try{const [nextGroups,nextProfiles]=await Promise.all([repository.groups(),repository.profiles()]);setGroups(nextGroups);setProfiles(nextProfiles);setError("")}catch(caught){setError(caught instanceof Error?caught.message:"Не удалось загрузить группы.")}},[repository]);
  useEffect(()=>{void load()},[load]);
  const act=async(action:()=>Promise<void>)=>{setBusy(true);setError("");try{await action();await load()}catch(caught){const message=caught instanceof Error?caught.message:"Не удалось выполнить действие.";setError(message.includes("STALE_")?"Данные уже изменил другой участник. Обновите страницу.":message)}finally{setBusy(false)}};
  if(!repository)return <main className="ladder"><button className="back" onClick={onBack}>← Все челленджи</button><section className="panel coopUnavailable"><p className="eyebrow">CO-OP MASTER ROTATION</p><h1>Нужен аккаунт</h1><p className="muted">Группы и приглашения доступны после входа в аккаунт.</p></section></main>;
  const pending=groups.filter(group=>group.members.find(member=>member.userId===userId)?.status==="pending");
  const active=groups.filter(group=>group.members.every(member=>member.status==="accepted"));
  const waiting=groups.filter(group=>!pending.includes(group)&&!active.includes(group));
  const open=active.find(group=>group.id===openId);
  if(open)return <Details group={open} repository={repository} busy={busy} error={error} act={act} reload={load} onBack={()=>setOpenId(null)}/>;
  return <main className="ladder"><button className="back" onClick={onBack}>← Все челленджи</button><div className="ladderHead"><div><p className="eyebrow">КОМАНДНОЕ ИСПЫТАНИЕ</p><h1>Co-op Master Rotation</h1><p>Освойте каждое Вознесение всеми персонажами каждого участника. Поражение сбрасывает общую ротацию.</p></div><button className="primary" onClick={()=>setCreating(true)}>+ Создать группу</button></div>
  {error&&<div className="errorBanner inlineError">{error} <button onClick={()=>void load()}>Обновить</button></div>}
  {pending.length>0&&<GroupSection title="Вас зовут в группу" eyebrow="ПРИГЛАШЕНИЯ">{pending.map(group=><div className="groupRow" key={group.id}><GroupName group={group}/><div><button className="ghost" disabled={busy} onClick={()=>void act(()=>repository.answer(group.id,false))}>Отклонить</button><button className="primary" disabled={busy} onClick={()=>void act(()=>repository.answer(group.id,true))}>Принять</button></div></div>)}</GroupSection>}
  <GroupSection title="Активные группы" eyebrow="ВАШИ ГРУППЫ">{active.length?active.map(group=><button className="groupCard" key={group.id} onClick={()=>setOpenId(group.id)}><div><h3>{group.name}</h3><p>{group.members.map(member=>`@${member.username}`).join(" · ")}</p></div><span>{group.initialized?`A${group.currentAscension} · 🧚 ${group.fairies}`:"Выбрать режим"}</span><button className="iconDanger" aria-label="Удалить группу" onClick={event=>{event.stopPropagation();if(confirm(`Удалить группу «${group.name}»?`))void act(()=>repository.remove(group.id))}}>×</button></button>):<div className="empty">Активных групп пока нет.</div>}</GroupSection>
  {waiting.length>0&&<GroupSection title="Ждём участников" eyebrow="ОЖИДАНИЕ">{waiting.map(group=><div className="groupRow" key={group.id}><GroupName group={group}/><button className="iconDanger" onClick={()=>{if(confirm(`Удалить группу «${group.name}»?`))void act(()=>repository.remove(group.id))}}>×</button></div>)}</GroupSection>}
  {creating&&<div className="modalShade" onClick={()=>setCreating(false)}><div className="modal createGroupModal" onClick={event=>event.stopPropagation()}><p className="eyebrow">НОВАЯ ГРУППА</p><h2>Соберите команду</h2><label>Название группы<input autoFocus maxLength={60} value={name} onChange={event=>setName(event.target.value)} placeholder="Например, Мастера Шпиля"/></label><p className="fieldLabel">Участники · выберите от 1 до 3</p><div className="profilePicker">{profiles.map(profile=><label key={profile.id}><input type="checkbox" checked={invited.includes(profile.id)} disabled={!invited.includes(profile.id)&&invited.length===3} onChange={()=>setInvited(current=>current.includes(profile.id)?current.filter(id=>id!==profile.id):[...current,profile.id])}/><span>@{profile.username}</span></label>)}</div><div><button className="ghost" onClick={()=>setCreating(false)}>Отмена</button><button className="primary" disabled={busy||!name.trim()||!invited.length} onClick={()=>void act(async()=>{await repository.create(name,invited);setCreating(false);setName("");setInvited([])})}>Создать и пригласить</button></div></div></div>}</main>;
}

function Details({group,repository,busy,error,act,reload,onBack}:{group:CoopMasterGroup;repository:CoopMasterRepository;busy:boolean;error:string;act:(fn:()=>Promise<void>)=>Promise<void>;reload:()=>Promise<void>;onBack:()=>void}){
  const [assignments,setAssignments]=useState<Record<string,CharacterId>>({}),[lossOpen,setLossOpen]=useState(false),[masterOpen,setMasterOpen]=useState(false),[historyPage,setHistoryPage]=useState(1);
  const stats=useMemo(()=>coopMasterStats(group),[group]);
  const completed=group.activeAttempt?.completed??{};
  const activeAssignments=group.activeAttempt?.assignments;
  const allAssigned=group.members.every(member=>assignments[member.userId]);
  const randomFor=(userId:string)=>{const available=characters.filter(character=>!(completed[userId]??[]).includes(character.id));setAssignments(current=>({...current,[userId]:available[Math.floor(Math.random()*available.length)].id}))};
  if(!group.initialized)return <main className="ladder masterRotation"><button className="back" onClick={onBack}>← Мои группы</button><div className="ladderHead"><div><p className="eyebrow">CO-OP MASTER ROTATION</p><h1>{group.name}</h1><p>{group.members.map(member=>`@${member.username}`).join(" · ")}</p></div></div>{error&&<ErrorBanner error={error} reload={reload}/>}<section className="modeChoice"><ModeCard mode="normal" action={()=>void act(()=>repository.initialize(group.id,"normal",group.updatedAt))}/><ModeCard mode="master" action={()=>setMasterOpen(true)}/></section>{masterOpen&&<ConfirmMaster cancel={()=>setMasterOpen(false)} confirm={()=>void act(async()=>{await repository.initialize(group.id,"master",group.updatedAt);setMasterOpen(false)})}/>}</main>;
  const finish=(result:"win"|"lose",fairy=false)=>void act(async()=>{await repository.finish(group.id,result,fairy,group.updatedAt);setLossOpen(false);setAssignments({})});
  return <main className="ladder masterRotation coopMaster"><button className="back" onClick={onBack}>← Мои группы</button><div className="ladderHead masterHead"><div><p className="eyebrow">CO-OP MASTER ROTATION · {group.members.length} ИГРОКА</p><h1>{group.name}</h1><p>{group.members.map(member=>`@${member.username}`).join(" · ")}</p></div><div className="masterScore"><span>A{group.currentAscension}</span><small>🧚 {group.fairies} Fairy in a Bottle</small></div></div>{error&&<ErrorBanner error={error} reload={reload}/>} 
  {group.completedA10Once&&group.mode==="normal"&&<section className="panel masteryOffer"><div><p className="eyebrow">ПОЗДРАВЛЯЕМ!</p><h2>A10 освоено всей группой</h2><p>Можно навсегда перейти в Master Mode.</p></div><button className="primary" disabled={!!group.activeAttempt} onClick={()=>setMasterOpen(true)}>Включить Master Mode</button></section>}
  {activeAssignments?<section className="activeRun"><div className="runTop"><div><p className="eyebrow">АКТИВНЫЙ КООПЕРАТИВНЫЙ ЗАБЕГ</p><h2>A{group.currentAscension}</h2><p className="muted">Одна победа засчитывает выбранного персонажа каждому игроку.</p></div><strong>{Object.values(completed).reduce((sum,ids)=>sum+ids.length,0)}/{group.members.length*characters.length}</strong></div><div className="activeRoster">{group.members.map(member=>{const character=getCharacter(activeAssignments[member.userId]);return <article className="activePlayerCard" key={member.userId} style={{"--character-color":character.color} as CSSProperties}><span className="activeCharacterIcon">{character.initials}</span><div><small>ИГРОК</small><h3>@{member.username}</h3><p>{character.name}</p></div></article>})}</div><div className="runActions"><button className="danger" disabled={busy} onClick={()=>setLossOpen(true)}>Поражение</button><button className="primary" disabled={busy} onClick={()=>finish("win")}>Победа</button></div></section>:<section className="panel characterSelection"><div className="panelHead"><div><p className="eyebrow">{group.activeAttempt?"ПРОДОЛЖИТЬ РОТАЦИЮ":"НОВАЯ ПОПЫТКА"}</p><h2>Выберите персонажей</h2></div></div><Progress group={group}/><div className="playerChoices">{group.members.map(member=><article className="playerChoiceCard" key={member.userId}><header className="playerIdentity"><span className="playerAvatar">{member.username.slice(0,2).toUpperCase()}</span><div><h3>@{member.username}</h3><p>{(completed[member.userId]??[]).length} из {characters.length} пройдено</p></div><button className="random" onClick={()=>randomFor(member.userId)}>⚄ Случайный</button></header><div className="characterPicker">{characters.map(character=>{const used=(completed[member.userId]??[]).includes(character.id);const selected=assignments[member.userId]===character.id;return <button key={character.id} disabled={used} className={`characterOption ${selected?"selected":""} ${used?"used":""}`} style={{"--character-color":character.color} as CSSProperties} onClick={()=>setAssignments(current=>({...current,[member.userId]:character.id}))}><span className="characterIcon">{used?"✓":character.initials}</span><span className="characterName">{character.name}</span><span className="selectionState">{used?"ПРОЙДЕН":selected?"ВЫБРАН":"ВЫБРАТЬ"}</span></button>})}</div></article>)}</div><button className="primary start" disabled={busy||!allAssigned} onClick={()=>void act(async()=>{await repository.start(group.id,assignments,group.updatedAt);setAssignments({})})}>Начать общий забег →</button></section>}
  <section className="panel"><div className="panelHead"><div><p className="eyebrow">КАРТА ОСВОЕНИЯ</p><h2>Путь A1–A10</h2></div></div><div className="masteryMap">{Array.from({length:10},(_,index)=>{const level=index+1;const done=group.mode==="master"||level<group.currentAscension;return <div key={level} className={done?"done":level===group.currentAscension?"current":""}><b>A{level}</b><small>{done?"Освоено":level===group.currentAscension?"Текущее":"Не достигнуто"}</small></div>})}</div></section>
  <section className="panel statCards coopMasterStats"><div><small>Максимум</small><b>A{group.maxAscension}</b></div><div><small>Fairy</small><b>{group.fairies}</b></div><div><small>Освоено</small><b>{stats.mastered}</b></div><div><small>Попыток</small><b>{stats.attempts}</b></div><div><small>Побед A10</small><b>{stats.successfulA10}</b></div><div><small>Серия A10</small><b>{stats.a10Streak}</b></div><div><small>Средний прогресс</small><b>{stats.averageProgress.toFixed(1)}</b></div></section>
  <section className="playerStatGrid">{stats.players.map(player=><article className="panel" key={player.member.userId}><p className="eyebrow">ИГРОК</p><h2>@{player.member.username}</h2><p className="muted">Лучший: {player.best?getCharacter(player.best.characterId).name:"—"} · Сложный: {player.hardest?getCharacter(player.hardest.characterId).name:"—"}</p><table><thead><tr><th>Персонаж</th><th>Победы</th><th>Винрейт</th><th>Макс.</th></tr></thead><tbody>{player.characterStats.map(item=><tr key={item.characterId}><td>{getCharacter(item.characterId).name}</td><td>{item.wins}</td><td>{(item.winRate*100).toFixed(0)}%</td><td>{item.maxAscension?`A${item.maxAscension}`:"—"}</td></tr>)}</tbody></table></article>)}</section>
  <section className="panel history masterHistory"><div className="panelHead"><div><p className="eyebrow">АРХИВ</p><h2>История попыток</h2></div></div>{group.history.length?group.history.slice((historyPage-1)*5,historyPage*5).map(item=><div className={`historyRow ${item.successful?"success":""}`} key={item.id}><div><b>A{item.ascension} · {Object.values(item.completed).reduce((sum,ids)=>sum+ids.length,0)} побед персонажами</b><small>{fmt.format(new Date(item.startedAt))} — {fmt.format(new Date(item.finishedAt))}</small></div><span>{item.successful?"✦ Вознесение освоено":item.fairyUsed?"🧚 Fairy использована":"Попытка провалена"}</span></div>):<div className="empty">Завершённых попыток пока нет.</div>}<div className="pager"><button disabled={historyPage===1} onClick={()=>setHistoryPage(historyPage-1)}>←</button><span>{historyPage} / {Math.max(1,Math.ceil(group.history.length/5))}</span><button disabled={historyPage>=Math.ceil(group.history.length/5)} onClick={()=>setHistoryPage(historyPage+1)}>→</button></div></section>
  {lossOpen&&<div className="modalShade" onClick={()=>setLossOpen(false)}><div className="modal" onClick={event=>event.stopPropagation()}><span className="modalIcon">!</span><h2>{group.fairies?"Использовать Fairy?":"Завершить попытку?"}</h2><p>{group.fairies?"Зелье сохранит Вознесение, но прогресс всех игроков будет сброшен.":`Прогресс группы сбросится, Вознесение снизится до A${Math.max(1,group.currentAscension-1)}.`}</p><div>{group.fairies?<><button className="ghost" onClick={()=>finish("lose",false)}>Не использовать</button><button className="primary" onClick={()=>finish("lose",true)}>Использовать</button></>:<><button className="ghost" onClick={()=>setLossOpen(false)}>Отмена</button><button className="danger" onClick={()=>finish("lose")}>Подтвердить</button></>}</div></div></div>}{masterOpen&&<ConfirmMaster cancel={()=>setMasterOpen(false)} confirm={()=>void act(async()=>{await repository.enableMaster(group.id,group.updatedAt);setMasterOpen(false)})}/>}</main>;
}

function Progress({group}:{group:CoopMasterGroup}){const done=Object.values(group.activeAttempt?.completed??{}).reduce((sum,ids)=>sum+ids.length,0),total=group.members.length*characters.length;return <div className="teamProgress"><div><b>Прогресс A{group.currentAscension}</b><span>{done} / {total} персонажей</span></div><progress max={total} value={done}/></div>}
function ModeCard({mode,action}:{mode:MasterRotationMode;action:()=>void}){const master=mode==="master";return <article className={master?"masterModeCard":""}><span className="modeRune">{master?"Ⅹ":"Ⅰ"}</span><p className="eyebrow">{master?"MASTER MODE":"ОБЫЧНЫЙ РЕЖИМ"}</p><h2>{master?"Сразу на A10":"Начать с A1"}</h2><p>{master?"Постоянное испытание на максимальном Вознесении. Выбор необратим.":"Постепенно освойте все Вознесения всей группой."}</p><button className={master?"danger":"primary"} onClick={action}>{master?"Выбрать Master Mode":"Начать освоение"}</button></article>}
function ConfirmMaster({cancel,confirm}:{cancel:()=>void;confirm:()=>void}){return <div className="modalShade" onClick={cancel}><div className="modal" onClick={event=>event.stopPropagation()}><span className="modalIcon">Ⅹ</span><h2>Включить Master Mode?</h2><p>Группа сразу перейдёт на A10. Выбор необратим.</p><div><button className="ghost" onClick={cancel}>Отмена</button><button className="danger" onClick={confirm}>Включить навсегда</button></div></div></div>}
function GroupSection({title,eyebrow,children}:{title:string;eyebrow:string;children:React.ReactNode}){return <section className="panel"><div className="panelHead"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div></div>{children}</section>}
function GroupName({group}:{group:CoopMasterGroup}){return <div><b>{group.name}</b><small>{group.members.map(member=>`@${member.username} — ${member.status==="accepted"?"принял":"ожидает"}`).join(" · ")}</small></div>}
function ErrorBanner({error,reload}:{error:string;reload:()=>Promise<void>}){return <div className="errorBanner inlineError">{error} <button onClick={()=>void reload()}>Обновить</button></div>}
