"use client";
import { CSSProperties, useMemo, useState } from "react";
import { characterById, characters } from "@/domain/ladder";
import { enableMasterMode, initializeMasterRotation, loseMasterCharacter, masterRotationStats, startMasterCharacter, winMasterCharacter } from "@/domain/masterRotation";
import { CharacterId, MasterRotationData } from "@/domain/types";

const fmt=new Intl.DateTimeFormat("ru-RU",{day:"2-digit",month:"short",year:"numeric"});
const getCharacter=(id:CharacterId)=>characterById(id);

export default function MasterRotationChallenge({data,onChange,onBack}:{data:MasterRotationData;onChange:(data:MasterRotationData)=>void;onBack:()=>void}){
  const [selected,setSelected]=useState<CharacterId|null>(null),[masterConfirm,setMasterConfirm]=useState(false),[lossConfirm,setLossConfirm]=useState(false),[page,setPage]=useState(1);
  const stats=useMemo(()=>masterRotationStats(data),[data]);
  const available=characters.filter(item=>!data.activeAttempt?.completedCharacters.includes(item.id));
  const active=data.activeAttempt?.activeCharacter?getCharacter(data.activeAttempt.activeCharacter):null;
  if(!data.initialized)return <main className="ladder masterRotation"><button className="back" onClick={onBack}>← Все челленджи</button><div className="ladderHead"><div><p className="eyebrow">НОВОЕ ИСПЫТАНИЕ</p><h1>Master Rotation</h1><p>Освойте каждое Вознесение всеми персонажами. Порядок выбираете вы, но поражение сбрасывает текущую ротацию.</p></div></div><section className="modeChoice"><article><span className="modeRune">Ⅰ</span><p className="eyebrow">ОБЫЧНЫЙ РЕЖИМ</p><h2>Начать с A1</h2><p>Постепенно пройдите путь до A10, завершая ротацию каждым персонажем.</p><button className="primary" onClick={()=>onChange(initializeMasterRotation("normal"))}>Начать освоение</button></article><article className="masterModeCard"><span className="modeRune">Ⅹ</span><p className="eyebrow">MASTER MODE</p><h2>Сразу на A10</h2><p>Постоянное испытание на максимальном Вознесении. Выбор необратим.</p><button className="danger" onClick={()=>setMasterConfirm(true)}>Выбрать Master Mode</button></article></section>{masterConfirm&&<MasterConfirm onCancel={()=>setMasterConfirm(false)} onConfirm={()=>onChange(initializeMasterRotation("master"))}/>}</main>;
  const chooseRandom=()=>setSelected(available[Math.floor(Math.random()*available.length)].id);
  const switchMaster=()=>{onChange(enableMasterMode(data));setMasterConfirm(false)};
  const finishLoss=(useFairy:boolean)=>{onChange(loseMasterCharacter(data,useFairy));setLossConfirm(false);setSelected(null)};
  return <main className="ladder masterRotation"><button className="back" onClick={onBack}>← Все челленджи</button><div className="ladderHead masterHead"><div><p className="eyebrow">ПОСЛЕДОВАТЕЛЬНОЕ ОСВОЕНИЕ</p><h1>Master Rotation</h1><p>Пройдите A{data.currentAscension} каждым персонажем. Победа закрепляет персонажа, поражение завершает всю попытку.</p></div><div className="masterScore"><span>A{data.currentAscension}</span><small>🧚 {data.fairies} Fairy in a Bottle</small></div></div>
  {data.completedA10Once&&data.mode==="normal"&&<section className="panel masteryOffer"><div><p className="eyebrow">ПОЗДРАВЛЯЕМ!</p><h2>Все Вознесения освоены</h2><p>Закрепите прогресс и проходите только A10 в постоянном Master Mode.</p></div><button className="primary" disabled={!!data.activeAttempt} onClick={()=>setMasterConfirm(true)}>Включить Master Mode</button></section>}
  {active?<section className="activeRun masterActive"><div className="runTop"><div className="portrait" style={{"--c":active.color} as CSSProperties}>{active.sigil}</div><div><p className="eyebrow">АКТИВНЫЙ ЗАБЕГ · A{data.currentAscension}</p><h2>{active.name}</h2><p className="muted">Пройдено в ротации: {data.activeAttempt!.completedCharacters.length} из {characters.length}</p></div><strong>{data.activeAttempt!.completedCharacters.length}/{characters.length}</strong></div><RotationRoster completed={data.activeAttempt!.completedCharacters} active={active.id}/><div className="runActions"><button className="danger" onClick={()=>setLossConfirm(true)}>Поражение</button><button className="primary" onClick={()=>{onChange(winMasterCharacter(data));setSelected(null)}}>{data.activeAttempt!.completedCharacters.length===characters.length-1?"Завершить ротацию":"Победа"}</button></div></section>:<section className="panel"><div className="panelHead"><div><p className="eyebrow">{data.activeAttempt?"ПРОДОЛЖИТЬ РОТАЦИЮ":"НОВАЯ ПОПЫТКА"}</p><h2>Выберите персонажа</h2></div><button className="random" onClick={chooseRandom}>⚄ Случайный персонаж</button></div><RotationRoster completed={data.activeAttempt?.completedCharacters??[]} active={null}/><div className="characters masterCharacters">{characters.map(character=>{const used=data.activeAttempt?.completedCharacters.includes(character.id);return <button key={character.id} disabled={used} onClick={()=>setSelected(character.id)} className={`${selected===character.id?"selected ":""}${used?"used":""}`} style={{"--c":character.color} as CSSProperties}><span>{character.sigil}</span><b>{character.name}</b><small>{used?"ПРОЙДЕН":selected===character.id?"ВЫБРАН":"ВЫБРАТЬ"}</small></button>})}</div><button className="primary start" disabled={!selected} onClick={()=>{if(selected)onChange(startMasterCharacter(data,selected))}}>Начать забег →</button></section>}
  {data.mode==="normal"&&!data.completedA10Once&&<section className="panel masteryOffer subdued"><div><p className="eyebrow">УЖЕ ГОТОВЫ К НАСТОЯЩЕМУ ИСПЫТАНИЮ?</p><h2>Перейти сразу на A10</h2><p>Master Mode необратим и доступен только между попытками.</p></div><button className="ghost" disabled={!!data.activeAttempt} onClick={()=>setMasterConfirm(true)}>Переключиться на Master Mode</button></section>}
  <section className="panel"><div className="panelHead"><div><p className="eyebrow">КАРТА ОСВОЕНИЯ</p><h2>Путь A1–A10</h2></div></div><div className="masteryMap">{Array.from({length:10},(_,index)=>{const level=index+1;const done=data.mode==="master"||level<data.currentAscension;const current=level===data.currentAscension;return <div key={level} className={done?"done":current?"current":""}><b>A{level}</b><small>{done?"Освоено":current?"Текущее":"Не достигнуто"}</small></div>})}</div></section>
  <section className="masterStats"><div className="panel statCards"><div><small>Максимум</small><b>A{data.maxAscension}</b></div><div><small>Fairy</small><b>{data.fairies}</b></div><div><small>Освоено ротаций</small><b>{stats.mastered}</b></div><div><small>Попыток</small><b>{stats.attempts}</b></div><div><small>Побед A10</small><b>{stats.successfulA10}</b></div><div><small>Серия A10</small><b>{stats.a10Streak}</b></div><div><small>Средний прогресс</small><b>{stats.averageProgress.toFixed(1)}</b></div></div><div className="panel highlights"><p className="eyebrow">ПЕРСОНАЖИ</p><h2>Лидеры ротации</h2><p>Лучший: <strong>{stats.best?getCharacter(stats.best.characterId).name:"—"}</strong></p><p>Самый сложный: <strong>{stats.hardest?getCharacter(stats.hardest.characterId).name:"—"}</strong></p></div></section>
  <section className="panel stats"><div className="panelHead"><div><p className="eyebrow">СТАТИСТИКА</p><h2>Персонажи</h2></div></div><table><thead><tr><th>Персонаж</th><th>Попытки</th><th>Победы</th><th>Винрейт</th><th>Макс.</th></tr></thead><tbody>{stats.characterStats.map(item=><tr key={item.characterId}><td><i style={{background:getCharacter(item.characterId).color}}/>{getCharacter(item.characterId).name}</td><td>{item.attempts}</td><td>{item.wins}</td><td>{(item.winRate*100).toFixed(0)}%</td><td>{item.maxAscension?`A${item.maxAscension}`:"—"}</td></tr>)}</tbody></table></section>
  <section className="panel history masterHistory"><div className="panelHead"><div><p className="eyebrow">АРХИВ</p><h2>История попыток</h2></div></div>{data.history.length?data.history.slice((page-1)*5,page*5).map(item=><div className={`historyRow ${item.successful?"success":""}`} key={item.id}><div><b>A{item.ascension} · {item.completedCharacters.map(id=>getCharacter(id).name).join(", ")||"нет побед"}</b><small>{fmt.format(new Date(item.startedAt))} — {fmt.format(new Date(item.finishedAt))}{item.lostCharacter?` · поражение: ${getCharacter(item.lostCharacter).name}`:""}</small></div><span>{item.successful?"✦ Ротация освоена":item.fairyUsed?"🧚 Fairy использована":"Попытка провалена"}</span></div>):<div className="empty">Завершённых попыток пока нет.</div>}<div className="pager"><button disabled={page===1} onClick={()=>setPage(page-1)}>←</button><span>{page} / {Math.max(1,Math.ceil(data.history.length/5))}</span><button disabled={page>=Math.ceil(data.history.length/5)} onClick={()=>setPage(page+1)}>→</button></div></section>
  {masterConfirm&&<MasterConfirm onCancel={()=>setMasterConfirm(false)} onConfirm={switchMaster}/>} {lossConfirm&&<div className="modalShade" onClick={()=>setLossConfirm(false)}><div className="modal" onClick={event=>event.stopPropagation()}><span className="modalIcon">!</span><h2>{data.fairies?"Использовать Fairy?":"Завершить попытку?"}</h2><p>{data.fairies?"Зелье сохранит текущее Вознесение, но прогресс ротации будет сброшен.":`Прогресс ротации сбросится, Вознесение снизится до A${Math.max(1,data.currentAscension-1)}.`}</p><div>{data.fairies?<><button className="ghost" onClick={()=>finishLoss(false)}>Не использовать</button><button className="primary" onClick={()=>finishLoss(true)}>Использовать зелье</button></>:<><button className="ghost" onClick={()=>setLossConfirm(false)}>Отмена</button><button className="danger" onClick={()=>finishLoss(false)}>Подтвердить поражение</button></>}</div></div></div>}</main>;
}

function RotationRoster({completed,active}:{completed:CharacterId[];active:CharacterId|null}){return <div className="rotationRoster">{characters.map(character=><div key={character.id} className={completed.includes(character.id)?"done":active===character.id?"active":""} style={{"--c":character.color} as CSSProperties}><span>{completed.includes(character.id)?"✓":character.sigil}</span><small>{character.name}</small></div>)}</div>}
function MasterConfirm({onCancel,onConfirm}:{onCancel:()=>void;onConfirm:()=>void}){return <div className="modalShade" onClick={onCancel}><div className="modal" onClick={event=>event.stopPropagation()}><span className="modalIcon">Ⅹ</span><h2>Включить Master Mode?</h2><p>Челлендж сразу перейдёт на A10. После подтверждения постепенное повышение Вознесения станет недоступно.</p><div><button className="ghost" onClick={onCancel}>Отмена</button><button className="danger" onClick={onConfirm}>Включить навсегда</button></div></div></div>}
