create table public.coop_master_groups (
  id uuid primary key default gen_random_uuid(), name text not null check(char_length(trim(name)) between 1 and 60), owner_id uuid not null references public.profiles(id),
  initialized boolean not null default false, mode text not null default 'normal' check(mode in ('normal','master')), current_ascension int not null default 1 check(current_ascension between 1 and 10),
  max_ascension int not null default 1 check(max_ascension between 1 and 10), fairies int not null default 0 check(fairies>=0), completed_a10_once boolean not null default false,
  active_attempt jsonb, history jsonb not null default '[]'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.coop_master_group_members (group_id uuid not null references public.coop_master_groups(id) on delete cascade,user_id uuid not null references public.profiles(id),status text not null check(status in ('pending','accepted','declined')),responded_at timestamptz,primary key(group_id,user_id));
alter table public.coop_master_groups enable row level security; alter table public.coop_master_group_members enable row level security;
create function public.is_coop_master_member(target_group_id uuid) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.coop_master_group_members where group_id=target_group_id and user_id=auth.uid() and status<>'declined')$$;
create policy "Members read coop master groups" on public.coop_master_groups for select using(public.is_coop_master_member(id));
create policy "Members delete coop master groups" on public.coop_master_groups for delete using(public.is_coop_master_member(id));
create policy "Members read coop master membership" on public.coop_master_group_members for select using(public.is_coop_master_member(group_id));
create policy "Invitees answer coop master invitations" on public.coop_master_group_members for update using(user_id=auth.uid() and status='pending') with check(user_id=auth.uid());
create function public.create_coop_master_group(group_name text,invited_user_ids uuid[]) returns uuid language plpgsql security definer set search_path='' as $$declare new_id uuid;begin if auth.uid() is null then raise exception 'Authentication required';end if;if cardinality(invited_user_ids)<1 or cardinality(invited_user_ids)>3 then raise exception 'A group requires 2 to 4 players';end if;if auth.uid()=any(invited_user_ids) or cardinality(invited_user_ids)<>(select count(distinct id) from unnest(invited_user_ids) id) then raise exception 'Players must be unique';end if;insert into public.coop_master_groups(name,owner_id) values(trim(group_name),auth.uid()) returning id into new_id;insert into public.coop_master_group_members values(new_id,auth.uid(),'accepted',now());insert into public.coop_master_group_members(group_id,user_id,status) select new_id,id,'pending' from unnest(invited_user_ids) id;return new_id;end$$;
create function public.lock_coop_master(target_group_id uuid,expected_updated_at timestamptz) returns public.coop_master_groups language plpgsql security definer set search_path='' as $$declare result public.coop_master_groups%rowtype;begin if not public.is_coop_master_member(target_group_id) then raise exception 'Not a member';end if;update public.coop_master_groups set updated_at=clock_timestamp() where id=target_group_id and updated_at=expected_updated_at returning * into result;if not found then raise exception 'STALE_GROUP';end if;return result;end$$;
create function public.initialize_coop_master(target_group_id uuid,chosen_mode text,expected_updated_at timestamptz) returns void language plpgsql security definer set search_path='' as $$declare g public.coop_master_groups%rowtype;begin g:=public.lock_coop_master(target_group_id,expected_updated_at);if chosen_mode not in ('normal','master') or (g.initialized and (g.mode='master' or g.active_attempt is not null)) then raise exception 'Invalid mode change';end if;update public.coop_master_groups set initialized=true,mode=chosen_mode,current_ascension=case when chosen_mode='master' then 10 else current_ascension end,max_ascension=case when chosen_mode='master' then 10 else max_ascension end where id=target_group_id;end$$;
create function public.start_coop_master_run(target_group_id uuid,chosen_assignments jsonb,expected_updated_at timestamptz) returns void language plpgsql security definer set search_path='' as $$declare g public.coop_master_groups%rowtype;member_count int;completed jsonb;begin g:=public.lock_coop_master(target_group_id,expected_updated_at);if not g.initialized then raise exception 'Challenge is not initialized';end if;select count(*) into member_count from public.coop_master_group_members where group_id=target_group_id and status='accepted';if member_count<>(select count(*) from public.coop_master_group_members where group_id=target_group_id and status<>'declined') or jsonb_object_length(chosen_assignments)<>member_count then raise exception 'Every accepted player needs a character';end if;completed:=coalesce(g.active_attempt->'completed','{}'::jsonb);if exists(select 1 from jsonb_each_text(chosen_assignments) a where a.value not in ('ironclad','silent','regent','necrobinder','defect') or not exists(select 1 from public.coop_master_group_members m where m.group_id=target_group_id and m.user_id::text=a.key and m.status='accepted') or coalesce(completed->a.key,'[]'::jsonb)?a.value) then raise exception 'Invalid assignments';end if;if g.active_attempt is null then g.active_attempt:=jsonb_build_object('id',gen_random_uuid(),'ascension',g.current_ascension,'completed','{}'::jsonb,'assignments',chosen_assignments,'startedAt',now());else g.active_attempt:=jsonb_set(g.active_attempt,'{assignments}',chosen_assignments);end if;update public.coop_master_groups set active_attempt=g.active_attempt where id=target_group_id;end$$;
create function public.advance_coop_master_run(target_group_id uuid,run_result text,use_fairy boolean,expected_updated_at timestamptz) returns void language plpgsql security definer set search_path='' as $$declare g public.coop_master_groups%rowtype;completed jsonb;member record;all_done boolean:=true;fairy_used boolean;record jsonb;begin g:=public.lock_coop_master(target_group_id,expected_updated_at);if g.active_attempt is null or g.active_attempt->'assignments' is null then raise exception 'STALE_RUN';end if;completed:=coalesce(g.active_attempt->'completed','{}'::jsonb);if run_result='win' then for member in select user_id from public.coop_master_group_members where group_id=target_group_id and status='accepted' loop completed:=jsonb_set(completed,array[member.user_id::text],coalesce(completed->member.user_id::text,'[]'::jsonb)||jsonb_build_array(g.active_attempt->'assignments'->>member.user_id::text),true);if jsonb_array_length(completed->member.user_id::text)<5 then all_done:=false;end if;end loop;if not all_done then update public.coop_master_groups set active_attempt=jsonb_set(jsonb_set(g.active_attempt,'{completed}',completed),'{assignments}','null'::jsonb) where id=target_group_id;return;end if;record:=jsonb_build_object('id',g.active_attempt->>'id','ascension',g.current_ascension,'completed',completed,'lostAssignments',null,'fairyUsed',false,'successful',true,'startedAt',g.active_attempt->>'startedAt','finishedAt',now());update public.coop_master_groups set active_attempt=null,history=jsonb_build_array(record)||history,current_ascension=case when mode='master' then 10 else least(10,current_ascension+1) end,max_ascension=greatest(max_ascension,case when mode='master' then 10 else least(10,current_ascension+1) end),fairies=fairies+1,completed_a10_once=completed_a10_once or current_ascension=10 where id=target_group_id;elsif run_result='lose' then fairy_used:=use_fairy and g.fairies>0;record:=jsonb_build_object('id',g.active_attempt->>'id','ascension',g.current_ascension,'completed',completed,'lostAssignments',g.active_attempt->'assignments','fairyUsed',fairy_used,'successful',false,'startedAt',g.active_attempt->>'startedAt','finishedAt',now());update public.coop_master_groups set active_attempt=null,history=jsonb_build_array(record)||history,fairies=fairies-case when fairy_used then 1 else 0 end,current_ascension=case when mode='master' or fairy_used then current_ascension else greatest(1,current_ascension-1) end where id=target_group_id;else raise exception 'Invalid result';end if;end$$;
revoke all on function public.create_coop_master_group(text,uuid[]) from public;revoke all on function public.lock_coop_master(uuid,timestamptz) from public;revoke all on function public.initialize_coop_master(uuid,text,timestamptz) from public;revoke all on function public.start_coop_master_run(uuid,jsonb,timestamptz) from public;revoke all on function public.advance_coop_master_run(uuid,text,boolean,timestamptz) from public;
grant execute on function public.create_coop_master_group(text,uuid[]) to authenticated;grant execute on function public.initialize_coop_master(uuid,text,timestamptz) to authenticated;grant execute on function public.start_coop_master_run(uuid,jsonb,timestamptz) to authenticated;grant execute on function public.advance_coop_master_run(uuid,text,boolean,timestamptz) to authenticated;
